attributes:
  metadata:
    restrictions:
      - condition: "settings:zabbix_monitoring == null or settings:zabbix_monitoring.metadata.enabled == false"
        action: disable
        message: "This plugin requires Zabbix plugin"
        strict: false
  community:
    value: "public"
    label: "SNMP community"
    description: "SNMP community for traps authorization"
    weight: 10
    type: "password"
